security:
  oauth2:
    client:
      registration:
        kakao:
          # kakao에서 제공
          client-id:
          # kakao에서 제공
          client-secret:
          # 인증 후 사용자가 리다이렉트 될 URI를 지정
          # kakao에 미리 등록해논 uri
          # 인증 및 권한 부여가 완료된 후에 사용자를 애플리케이션으로 다시 리다이렉트하는 URI
          redirect-uri:
          # 클라이언트 인증 방법 지정
          client-authentication-method: POST
          # 코드 기반 인증 사용
          authorization-grant-type: authorization_code
          # 동의 항목
          scope: profile_nickname, profile_image, account_email, gender, age_range
          client-name: Kakao
      provider:
        kakao:
          # 사용자 인증을 위해 리다이렉션될 Kakao의 인증 URI를 지정
          authorization-uri:
          # 액세스 토큰을 받기 위한 Kakao의 토큰 요청 URI를 지정
          token-uri:
          # 인증된 사용자의 정보를 가져오는 Kakao의 사용자 정보 요청 URI를 지정 (사용자를 인증 서버로 보내는 첫 단계의 URI)
          user-info-uri:
          # Kakao에서 제공하는 사용자 정보 중에서 사용자 이름을 나타내는 속성을 지정
          user-name-attribute: